version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: terraform
  directories:
  - /modules/eventbridge-event-bus
  - /modules/eventbridge-rule
  - /modules/msk-cluster
  - /modules/sns-fifo-topic
  - /modules/sns-standard-topic
  schedule:
    interval: weekly
