# Modules
- color: "fbca04"
  description: "This issue or pull request is related to eventbridge-event-bus module."
  name: ":floppy_disk: eventbridge-event-bus"
- color: "fbca04"
  description: "This issue or pull request is related to eventbridge-rule module."
  name: ":floppy_disk: eventbridge-rule"
- color: "fbca04"
  description: "This issue or pull request is related to msk-cluster module."
  name: ":floppy_disk: msk-cluster"
- color: "fbca04"
  description: "This issue or pull request is related to ses-identity module."
  name: ":floppy_disk: ses-identity"
- color: "fbca04"
  description: "This issue or pull request is related to sns-fifo-topic module."
  name: ":floppy_disk: sns-fifo-topic"
- color: "fbca04"
  description: "This issue or pull request is related to sns-standard-topic module."
  name: ":floppy_disk: sns-standard-topic"
